version: "3.9"

services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "4000:4000"
    depends_on:
      - service_users
      - service_orders
    environment:
      - PORT=4000
      - USERS_URL=http://service_users:4001
      - ORDERS_URL=http://service_orders:4002
      - JWT_SECRET=supersecretkey

  service_users:
    build: ./service_users
    container_name: service_users
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - JWT_SECRET=supersecretkey

  service_orders:
    build: ./service_orders
    container_name: service_orders
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - JWT_SECRET=supersecretkey
